version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
      - .env.local
